<template>
  <v-container fluid>
    <h4>Use 'card' for wrapping content into Groups</h4>
    
    <!-- FORM-BASE-COMPONENT -->    
    <v-form-base :value="myValue" :schema="mySchema" @input="log"/>
    
    <!-- Stuff  -->    
    <infoline :value="myValue" :schema="mySchema" :path="$options._componentTag"/>
  </v-container>
</template>

<script>
import VFormBase from '@/components/vFormBase'
import Infoline from '@/components/infoline'
import log from '@/lib'

export default {
  name: 'Cards',
  components: { VFormBase, Infoline },
  data () {
    return {
      myValue: {
        group1:{ name:'Taleb', read:true, book:'A'},  
        group2:{ name:'Jobs', read:true, book:'B' },  
        group3:{ name:'Harari', read:false, book:'C' },  
      },      
      mySchema: {
        // autogenerated inner schema
        group1: { type: 'card', flex:6, class:'ma-2 pa-2', color:'grey lighten-3' },

        // with defined inner schema, displays only defined props
        group2: { type: 'card', offset:1, flex:5, hover:true, class:'ma-2 pa-2', color:'red lighten-4',
          schema: {
            read: { type: 'checkbox', label: 'Ok', color: 'red', flex: 12 },
            name: { type: 'text', color: 'red', flex:12 },    
          }
        },
        group3: { type: 'card', title:'Title', subtitle:'Subtitle',  hover:true, class:'ma-2 pa-2', color:'blue lighten-4',
          schema: {
            name: { type: 'text', color: 'blue' },    
            read: { type: 'checkbox', label: 'Ok', color: 'blue' },
            book: { type: 'text', color: 'blue' },    
          }
        }
      }
    }
  },
  methods: {
    log
  }
}
</script>
