<template>
  <v-container fluid>
    <h4>Use Type 'card' for wrapping content into Groups with Card-Design</h4>
    
    <!-- FORM-BASE-COMPONENT -->    
    <v-form-base :value="myValue" :schema="mySchema" @input="log"/>
    
    <!-- Stuff  -->    
    <infoline :value="myValue" :schema="mySchema" :path="$options._componentTag"/>
  </v-container>
</template>

<script>
import VFormBase from '@/components/vFormBase'
import Infoline from '@/components/infoline'
import log from '@/lib'

export default {
  name: 'Cards',
  components: { VFormBase, Infoline },
  data () {
    return {
      myValue: {
        groupCard1:{ name:'Harari', read:false, book:'C' },  
        groupCard2:{ 
          tasks:[
            { name:'Jobs', read:true,},
            { name:'Harari', read:false,},
            { name:'Taleb', read:true,},
          ]
        },  
        groupCard3:{ name:'Jobs', read:true, book:'B' },  
      },      
      mySchema: {
        groupCard1: { type: 'card', elevation:8, title:'Card', subtitle:'Elevation 8',  hover:true, class:'ma-2 pa-2', color:'blue lighten-4',
          schema: {
            name: { type: 'text', color: 'blue' },    
            read: { type: 'checkbox', label: 'Ok', color: 'blue' },
            book: { type: 'text', color: 'blue' },    
          }
        },
        // array schema -> inner schema (shorthand type)
        groupCard2: { type: 'card', title:'Array', flex:6, class:'ma-2 pa-2', color:'grey lighten-3',schema: { 
          tasks: { type:'array', schema: { name:'text', read:'checkbox'}}
        } },

        // autogenerated inner schema
        groupCard3: { type: 'card', title:'Autogenerated', offset:3, flex:6, hover:true, class:'ma-2 pa-2', color:'red lighten-4',
          // schema: {
          //   read: { type: 'checkbox', label: 'Ok', color: 'red', flex: 12 },
          //   name: { type: 'text', color: 'red', flex:12 },    
          // }
        },
      }
    }
  },
  methods: {
    log
  }
}
</script>
