<style>
  .br-8 { border-radius: 8px;}
</style>

<template>
  <v-container fluid>
    <h4>Use Type 'group' for wrapping content into Groups with Card-Design</h4>
    
    <!-- FORM-BASE-COMPONENT -->    
    <v-form-base id="group"  :value="myValue" :schema="mySchema" @input:group="log"/>
    
    <!-- Stuff  -->    
    <infoline :value="myValue" :schema="mySchema" :path="$options._componentTag"/>
  </v-container>
</template>

<script>
  import VFormBase from '@/components/vFormBase'
  import Infoline from '@/components/infoline'
  import log from '@/lib'

  export default {
    name: 'Groups',
    components: { VFormBase, Infoline },
    data () {
      return {

        myValue: {
          card1:{ name:'Harari', read:false, book:'Homo Deus' },  
          card2:{ 
            tasks:[
              { name:'Jobs', read:true,},
              { name:'Harari', read:false,},
              { name:'Taleb', read:true,},
            ]
          },  
          card3:{ name:'Jobs', read:true, book:'My Apple' },  
        }, 

        mySchema: {
          card1: { type:'group', label:'<u>Base</u>', flex:5, class:'title pa-2 elevation-4 red--text red lighten-4', 
            schema: {
              name: { type: 'text', color: 'red', label:'Name'},    
              read: { type: 'checkbox', label: 'Ok', color: 'red' },
              book: { type: 'text', color: 'red', label:'Book' },    
            }
          },
          // array schema -> inner schema (shorthand type)
          card2: { type: 'group', label:'Array', flex:6, class:'title br-8 elevation-4 mx-2 pa-2 lighten-3 green',schema: { 
            tasks: { type:'array', schema: { name:'text', read:'checkbox'}}
          } },

          // autogenerated inner schema
          card3: { type: 'group', label:'Autogenerated', offset:'3', flex:6, class:'title ma-2 pa-2 blue lighten-4',
            // schema: {
            //   read: { type: 'checkbox', label: 'Ok', color: 'blue', flex: 12 },
            //   name: { type: 'text', color: 'blue', flex:12 },    
            // }
          },
        }
      }
    },
    methods: {
      log
    }
  }
</script>
