<style>
  .br-8 { border-radius: 8px;}
</style>

<template>
  <v-container fluid>
    <h4>Use Type 'group' for wrapping content into Groups and center all with 'row' Attribute</h4>
    
    <!-- FORM-BASE-COMPONENT -->    
    <v-form-base 
      id="group"  
      :model="myValue" 
      :schema="mySchema" 
      :col=4
      :row="{align:'center', justify:'center', noGutters:false}" 
      @input:group="log"
    />
    <!-- 
      See for handling <v-row></v-row>
      https://vuetifyjs.com/en/components/grids/ 
    -->
    
    
    
    <!-- Stuff  -->    
    <infoline :value="myValue" :schema="mySchema" :path="$options._componentTag"/>
  </v-container>
</template>

<script>
  import VFormBase from '@/components/vFormBase'
  import Infoline from '@/components/infoline'
  import log from '@/lib'

  export default {
    name: 'Groups',
    components: { VFormBase, Infoline },
    data () {
      return {

        myValue: {
          card1:{ name:'Harari' , read:true, book:'Homo Deus' },  
          card2:{ 
            tasks:[
              { name:'Jobs', read:true,},
              { name:'Harari', book:'Homo Deus', read:false,},
              { name:'Taleb', book:'Black Swan', read:true,},
            ]
          },  
          card3:{ name:'Jobs', read:true, book:'My Apple' },  
        }, 

        mySchema: {
          card1: { type:'group', label:'<u>Base</u>', col:5, class:'title pa-2 elevation-4 red--text red lighten-4', 
            schema: {
              name: { type: 'text', label:'Name' },    
              read: { type: 'checkbox', label: 'Ok', color: 'red' },
              book: { type: 'text',  label:'Book' },    
            }
          },
          // array schema -> inner schema (shorthand type)
          card2: { type: 'group', label:'Array', col:5, class:'title br-8 elevation-4 mx-1 pa-2 lighten-3 green',
            schema: { 
              tasks: { type:'array', col:12, row:{ noGutters:false }, schema: { read:{ type:'checkbox', col:2 } , name: { type:'text', col:5 }, book: { type:'text', col:5 } }}
            } 
          },
          // no defined schema - autogenerated schema
          card3: { type: 'group', label:'Autogenerated', col:5, class:'title ma-2 pa-2 blue lighten-4' },
        }
      }
    },
    methods: {
      log
    }
  }
</script>
